name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "terraform-s3-state-20240"
  AWS_DYNAMODB_TABLE: "LockPrevention_table"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create initial Terraform state file
        run: echo '{}' > terraform.tfstate && aws s3 cp terraform.tfstate s3://terraform-s3-state-20240/terraform.tfstate

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="dynamodb_table=${{ env.AWS_DYNAMODB_TABLE }}" -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve

      - name: Persist Terraform State
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: aws s3 cp terraform.tfstate s3://terraform-s3-state-20240/terraform.tfstate
